### ISSUE TITLE
[Filtering Subprocess] Filter by exact date match does not work for *datetime*

### ISSUE THREAD

**Issue by GalenkoEugene** [rubygarage/boilerplate#234]
### Description
Filter by exact date does not work, eg `filter[created_at-eq]=DATA_IN_JSON_FORMAT`
Predicate `eq` matches by exact value, since created_at/updated_at stores in DateTime format, it's never matching and always gives an empty result.

**Comment by WoLkErSs** [comment]
Resolved in [PR](https://github.com/rubygarage/boilerplate/pull/292)
